name: Update Database
on:
  push:
    branches:
      - main
      - test
    paths:
      - "requests/*.csv"

jobs:
  update-database:
    if: |
      github.event_name == 'push' &&
      (github.ref_name == 'main' || github.ref_name == 'test') &&
      github.actor != 'nd-0r-test' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DATABASE_UPDATE }}
          fetch-depth: 2

      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "accounter"
          out-file-path: "./accounter-exe"
          token: ${{ secrets.DATABASE_UPDATE }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.1
        with:
          separator: '\n'

      - name: Update database
        run: |
          chmod +x ./accounter-exe/accounter
          git checkout -b '${{ github.ref_name }}'
          git config --global user.email "aorals2@illinois.edu"
          git config --global user.name "Andrew Orals"

          CHANGED=$(printf %b '${{ steps.changed-files.outputs.all_changed_files }}')
          NUM_CHANGED=$(echo "$CHANGED" | wc -l)
          if [ $NUM_CHANGED -ne 1 ]; then
            echo "::error Too many files - only submit one file"
            exit 1
          fi
          CHANGED_ARGS=$(echo "$CHANGED" | xargs -d '\n')
          USERNAME=$(git --no-pager log --pretty=format:'%an' --diff-filter=A -- "$CHANGED_ARGS")
          ./accounter-exe/accounter --database ./account.sqlite --filename "$CHANGED_ARGS" --user "$USERNAME" --markdown ./README.md > ./balance.csv

          git rm "$CHANGED"
          git add README.md balance.csv account.sqlite
          git commit -m "ACCOUNTANT: add transaction"
          git push https://nd-0r-test:${{ secrets.DATABASE_UPDATE }}@github.com/aaaapartment/apartment-accounting.git

